// lib/core/constants/careers.dart

const List<String> careers = [
  'Business Administration',
  'Economics',
  'Biology',
  'Physics',
  'Geosciences',
  'Mathematics',
  'Microbiology',
  'Chemistry',
  'Medicine',
  'Architecture',
  'Art',
  'Design',
  'Art History',
  'Literature',
  'Music',
  'Digital Narratives',
  'Environmental Engineering',
  'Biomedical Engineering',
  'Civil Engineering',
  'Electrical Engineering',
  'Electronic Engineering',
  'Industrial Engineering',
  'Mechanical Engineering',
  'Chemical Engineering',
  'Systems and Computing Engineering',
  'Data Science',
  'Law',
  'Anthropology',
  'Political Science',
  'Global Studies',
  'Philosophy',
  'History',
  'Languages and Culture',
  'Psychology',
  'Art Education',
  'Biology Education',
  'Early Childhood Education',
  'Spanish and Philology Education',
  'Philosophy Education',
  'Physics Education',
  'History Education',
  'Mathematics Education',
  'Chemistry Education',
  'Global Environmental Change',
];
